In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('../Fresh_Start/all_items_per_shop_train_and_test.csv')
data

          shop_id  item_id  date_block_num  item_cnt_day
0               0        0               0           0.0
1               0        0               1           0.0
2               0        0               2           0.0
3               0        0               3           0.0
4               0        0               4           0.0
...           ...      ...             ...           ...
46553520       59    22169              29           0.0
46553521       59    22169              30           0.0
46553522       59    22169              31           0.0
46553523       59    22169              32           0.0
46553524       59    22169              33           0.0

[46553525 rows x 4 columns]

In [6]:
items = pd.read_csv('../csv_folder/items.csv')
items

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40
1,!ABBYY FineReader 12 Professional Edition Full...,1,76
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40
4,***КОРОБКА (СТЕКЛО) D,4,40
...,...,...,...
22165,"Ядерный титбит 2 [PC, Цифровая версия]",22165,31
22166,Язык запросов 1С:Предприятия [Цифровая версия],22166,54
22167,Язык запросов 1С:Предприятия 8 (+CD). Хрустале...,22167,49
22168,Яйцо для Little Inu,22168,62
22169,Яйцо дракона (Игра престолов),22169,69

In [8]:
df = pd.merge(data, items, left_on=['item_id'], right_on=['item_id'], how='inner')
df

,shop_id,item_id,date_block_num,item_cnt_day,item_name,item_category_id
0,0,0,0,0.0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,40
1,0,0,1,0.0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,40
2,0,0,2,0.0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,40
3,0,0,3,0.0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,40
4,0,0,4,0.0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,40
...,...,...,...,...,...,...
46553520,59,22169,29,0.0,Яйцо дракона (Игра престолов),69
46553521,59,22169,30,0.0,Яйцо дракона (Игра престолов),69
46553522,59,22169,31,0.0,Яйцо дракона (Игра престолов),69
46553523,59,22169,32,0.0,Яйцо дракона (Игра престолов),69
46553524,59,22169,33,0.0,Яйцо дракона (Игра престолов),69

In [9]:
df = df.drop(columns=['item_name'])

In [12]:
df = df.pivot_table(index = ['shop_id', 'item_category_id', 'item_id'],
                     values = ['item_cnt_day'],
                     columns = ['date_block_num'],
                     fill_value = 0,
                     aggfunc='sum')
df

                                 item_cnt_day                             ...  \
date_block_num                             0  1  2  3  4  5  6  7  8  9   ...
shop_id item_category_id item_id                                          ...
0       0                5441               0  0  0  0  0  0  0  0  0  0  ...
                         16255              0  1  0  0  0  0  0  0  0  0  ...
                         16256              0  0  0  0  0  0  0  0  0  0  ...
                         16257              0  0  0  0  0  0  0  0  0  0  ...
        1                5606               0  0  0  0  0  0  0  0  0  0  ...
...                                       ... .. .. .. .. .. .. .. .. ..  ...
59      83               22095              0  0  0  0  0  0  0  0  0  0  ...
                         22096              0  0  0  0  0  0  0  0  0  0  ...
                         22097              0  0  0  0  0  0  0  0  0  0  ...
                         22098              0  0  0  0  0  0  0  0  0  0  ...
                         22099              0  0  0  0  0  0  0  0  0  0  ...


date_block_num                   24 25 26 27 28 29 30 31 32 33
shop_id item_category_id item_id
0       0                5441     0  0  0  0  0  0  0  0  0  0
                         16255    0  0  0  0  0  0  0  0  0  0
                         16256    0  0  0  0  0  0  0  0  0  0
                         16257    0  0  0  0  0  0  0  0  0  0
        1                5606     0  0  0  0  0  0  0  0  0  0
...                              .. .. .. .. .. .. .. .. .. ..
59      83               22095    0  0  0  0  0  0  0  0  0  0
                         22096    0  0  0  0  0  0  0  0  0  0
                         22097    0  0  0  0  0  0  0  0  0  0
                         22098    0  0  0  0  0  0  0  0  0  0
                         22099    0  0  0  0  0  0  0  0  0  0

[1330200 rows x 34 columns]

In [16]:
df.columns = list(range(34))

In [22]:
df.head(50)

                                  0   1   2   3   4   5   6   7   8   9   ...  \
shop_id item_category_id item_id                                          ...
0       0                5441      0   0   0   0   0   0   0   0   0   0  ...
                         16255     0   1   0   0   0   0   0   0   0   0  ...
                         16256     0   0   0   0   0   0   0   0   0   0  ...
                         16257     0   0   0   0   0   0   0   0   0   0  ...
        1                5606      0   0   0   0   0   0   0   0   0   0  ...
                         5740      0   1   0   0   0   0   0   0   0   0  ...
        2                5570      0   1   0   0   0   0   0   0   0   0  ...
                         5571      0   0   0   0   0   0   0   0   0   0  ...
                         5572     10  11   0   0   0   0   0   0   0   0  ...
                         5573      1   1   0   0   0   0   0   0   0   0  ...
                         5574      0   3   0   0   0   0   0   0   0   0  ...
                         5575      4   0   0   0   0   0   0   0   0   0  ...
                         5576      5   2   0   0   0   0   0   0   0   0  ...
                         5607      0   0   0   0   0   0   0   0   0   0  ...
                         5608      0   0   0   0   0   0   0   0   0   0  ...
                         5609      1   1   0   0   0   0   0   0   0   0  ...
                         5610      0   1   0   0   0   0   0   0   0   0  ...
                         5611      0   0   0   0   0   0   0   0   0   0  ...
                         5612      1   0   0   0   0   0   0   0   0   0  ...
                         5613      0   0   0   0   0   0   0   0   0   0  ...
                         5614      0   0   0   0   0   0   0   0   0   0  ...
                         5615      0   0   0   0   0   0   0   0   0   0  ...
                         5616      0   0   0   0   0   0   0   0   0   0  ...
                         5617      0   0   0   0   0   0   0   0   0   0  ...
                         5618      0   0   0   0   0   0   0   0   0   0  ...
                         5619      0   0   0   0   0   0   0   0   0   0  ...
                         5620      0   0   0   0   0   0   0   0   0   0  ...
                         5621      0   0   0   0   0   0   0   0   0   0  ...
                         5622      0   0   0   0   0   0   0   0   0   0  ...
                         5623      1   3   0   0   0   0   0   0   0   0  ...
                         5624      0   0   0   0   0   0   0   0   0   0  ...
                         5625      0   0   0   0   0   0   0   0   0   0  ...
                         5626      0   0   0   0   0   0   0   0   0   0  ...
                         5627      2   4   0   0   0   0   0   0   0   0  ...
                         5628      0   0   0   0   0   0   0   0   0   0  ...
                         5629      9   5   0   0   0   0   0   0   0   0  ...
                         5630      1   1   0   0   0   0   0   0   0   0  ...
                         5631      0   0   0   0   0   0   0   0   0   0  ...
                         5632      3   1   0   0   0   0   0   0   0   0  ...
                         5633      0   0   0   0   0   0   0   0   0   0  ...
                         5634      0   0   0   0   0   0   0   0   0   0  ...
                         5635      2   1   0   0   0   0   0   0   0   0  ...
                         5636      0   2   0   0   0   0   0   0   0   0  ...
                         5637      0   0   0   0   0   0   0   0   0   0  ...
                         5638      0   0   0   0   0   0   0   0   0   0  ...
                         5639      0   0   0   0   0   0   0   0   0   0  ...
                         5640      0   0   0   0   0   0   0   0   0   0  ...
                         5641      1   0   0   0   0   0   0   0   0   0  ...
                         5642      0   1   0   0   0   0   0   0   0   0  ...
                         5643      6   3   0   0   0   0   0   0   0   0  ...

                                  24  25  26  27  28  29  30  31  32  33
shop_id item_category_id item_id
0       0                5441      0   0   0   0   0   0   0   0   0   0
                         16255     0   0   0   0   0   0   0   0   0   0
                         16256     0   0   0   0   0   0   0   0   0   0
                         16257     0   0   0   0   0   0   0   0   0   0
        1                5606      0   0   0   0   0   0   0   0   0   0
                         5740      0   0   0   0   0   0   0   0   0   0
        2                5570      0   0   0   0   0   0   0   0   0   0
                         5571      0   0   0   0   0   0   0   0   0   0
                         5572      0   0   0   0   0   0   0   0   0   0
                         5573      0   0   0   0   0   0   0   0   0   0
                         5574      0   0   0   0   0   0   0   0   0   0
                         5575      0   0   0   0   0   0   0   0   0   0
                         5576      0   0   0   0   0   0   0   0   0   0
                         5607      0   0   0   0   0   0   0   0   0   0
                         5608      0   0   0   0   0   0   0   0   0   0
                         5609      0   0   0   0   0   0   0   0   0   0
                         5610      0   0   0   0   0   0   0   0   0   0
                         5611      0   0   0   0   0   0   0   0   0   0
                         5612      0   0   0   0   0   0   0   0   0   0
                         5613      0   0   0   0   0   0   0   0   0   0
                         5614      0   0   0   0   0   0   0   0   0   0
                         5615      0   0   0   0   0   0   0   0   0   0
                         5616      0   0   0   0   0   0   0   0   0   0
                         5617      0   0   0   0   0   0   0   0   0   0
                         5618      0   0   0   0   0   0   0   0   0   0
                         5619      0   0   0   0   0   0   0   0   0   0
                         5620      0   0   0   0   0   0   0   0   0   0
                         5621      0   0   0   0   0   0   0   0   0   0
                         5622      0   0   0   0   0   0   0   0   0   0
                         5623      0   0   0   0   0   0   0   0   0   0
                         5624      0   0   0   0   0   0   0   0   0   0
                         5625      0   0   0   0   0   0   0   0   0   0
                         5626      0   0   0   0   0   0   0   0   0   0
                         5627      0   0   0   0   0   0   0   0   0   0
                         5628      0   0   0   0   0   0   0   0   0   0
                         5629      0   0   0   0   0   0   0   0   0   0
                         5630      0   0   0   0   0   0   0   0   0   0
                         5631      0   0   0   0   0   0   0   0   0   0
                         5632      0   0   0   0   0   0   0   0   0   0
                         5633      0   0   0   0   0   0   0   0   0   0
                         5634      0   0   0   0   0   0   0   0   0   0
                         5635      0   0   0   0   0   0   0   0   0   0
                         5636      0   0   0   0   0   0   0   0   0   0
                         5637      0   0   0   0   0   0   0   0   0   0
                         5638      0   0   0   0   0   0   0   0   0   0
                         5639      0   0   0   0   0   0   0   0   0   0
                         5640      0   0   0   0   0   0   0   0   0   0
                         5641      0   0   0   0   0   0   0   0   0   0
                         5642      0   0   0   0   0   0   0   0   0   0
                         5643      0   0   0   0   0   0   0   0   0   0

[50 rows x 34 columns]